name: Build & Push to ACR 

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  ACR_NAME: cometops
  ACR_SERVER: cometops.azurecr.io
  BACKEND_IMAGE: final/backend
  FRONTEND_IMAGE: final/frontend
  BACKEND_TAG: latest
  FRONTEND_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Login using client secret JSON (NOT OIDC)
      - name: Azure login (client secret)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR docker login
        run: az acr login -n "$ACR_NAME"

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ${{ env.ACR_SERVER }}/${{ env.BACKEND_IMAGE }}:${{ env.BACKEND_TAG }}

      - name: Build & push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ${{ env.ACR_SERVER }}/${{ env.FRONTEND_IMAGE }}:${{ env.FRONTEND_TAG }}